server:
  port: 8081

spring:
  application:
    name: second_hand1
  mvc:
    dispatch-options-request: true
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  mail:
    host: smtp.qq.com
    port: 465
    username: 1205337170@qq.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
mybatis:
  mapper-locations: 'classpath*:/mappers/**/*Mapper.xml'
  configuration:
    map-underscore-to-camel-case: true
dataSource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/second_hand1?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai
  username: root
  password: 234
  initialSize: 5
  minIdle: 5
  maxActive: 10
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  poolPreparedStatements: false
  timeBetweenLogStatsMillis: 0
  filters: mergeStat
  connectionProperties: druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000;keepAlive=true
  validationQuery: select 1
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  connectionErrorRetryAttempts: 3
  timeBetweenConnectErrorMillis: 30000
  breakAfterAcquireFailure: true
logging:
  config: classpath:logback-local.xml
  file:
    path: ./logs

jwt:
  secret: secondhand # JWT密钥，用于签名和验证令牌
  expiration-time: 3600000 # 令牌过期时间，单位为毫秒（例如：1小时）