CREATE TABLE product_reviews (
	review_id INT PRIMARY KEY AUTO_INCREMENT COMMENT '评论ID',
	product_id INT COMMENT '商品ID',
	user_id INT COMMENT '用户ID',
	rating INT CHECK (rating >= 1
	AND rating <= 5) COMMENT '评分',
	comment TEXT COMMENT '评论内容',
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '商品评论表';