CREATE TABLE shopping_carts (
	cart_id INT PRIMARY KEY AUTO_INCREMENT COMMENT '购物车ID',
	user_id INT COMMENT '用户ID',
	product_id INT COMMENT '商品ID',
	quantity INT NOT NULL COMMENT '商品数量',
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '购物车信息表';