CREATE TABLE user_favorites (
	favorite_id INT PRIMARY KEY AUTO_INCREMENT COMMENT '收藏ID',
	user_id INT COMMENT '用户ID',
	product_id INT COMMENT '商品ID',
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '用户收藏表';